port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
geodata-mode: true
geodata-loader: memconservative
tcp-concurrent: true
find-process-mode: 'off'
allow-lan: true
bind-address: "*"
mode: rule
log-level: silent
ipv6: false
unified-delay: false
global-client-fingerprint: none
keep-alive-interval: 15
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: "123456"
profile:
  store-selected: true
  store-fake-ip: false
sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - "+.jd.com"
  - dlg.io.mi.com
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  prefer-h3: false
  use-hosts: true
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 192.168.8.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
  - 192.168.8.1
  nameserver-policy:
  geosite:oisd-full,rule-ads: rcode://success
  proxy-server-nameserver:
  - 1.0.0.1
  - 8.8.4.4
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net


proxy-providers:
  VVIP-IPTUNNELS-FREE:
    type: http
    url: "https://raw.githubusercontent.com/marieff/cfaku/main/proxy/vvip-free.yaml"
    interval: 3600
    path: "./proxy_provider/vvip-free.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  VVIP-IPTUNNELS-VIP:
    type: file
    path: "./proxy_provider/vvip-vip.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  VVIP-IPTUNNELS-FOOL:
    type: http
    url: "http://fool.azurewebsites.net/get?cc=SG,ID&mode=cdn&pass=74a12fd6&format=clash&cdn=ilmupedia.mdevz.biz.id"
    interval: 3600
    path: "./proxy_provider/vvip-fool.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
      
rule-providers:
  rule_whatsapp:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_whatsapp.yaml
    path: "./rule_whatsapp.yaml"
    interval: 86400
  #rule_basicads:
    #type: http
    #behavior: classical
    #url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_basicads.yaml
    #path: "./rule_basicads.yaml"
    #interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_portgames.yaml
    path: "./rule_portgames.yaml"
    interval: 86400
  rule_bank-id:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_bank-id.yaml
    path: "./rule_bank-id.yaml"
    interval: 86400
  rule_indo:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_indo.yaml
    path: "./rule_indo.yaml"
    interval: 86400
    
proxy-groups:
- name: Global
  type: select
  disable-udp: false
  proxies:
  - BEST-PING
  - LOAD-BALANCE
  - FALLBACK
  - PROXY-CHAIN
  - SELECT
- name: SELECT
  type: select
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
#- name: AdBlock
  #type: select
  #disable-udp: false
  #proxies:
  #- REJECT
  #- Global
- name: Select_VIP
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-VIP
  url: http://www.gstatic.com/generate_204
  interval: 600
- name: LOAD-BALANCE
  type: load-balance
  strategy: round-robin
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: FALLBACK
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: BEST-PING 
  type: url-test
  tolerance: 50
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: PROXY-CHAIN
  type: relay
  disable-udp: false
  proxies:
  - BEST-PING
  - LOAD-BALANCE
  - FALLBACK

rules:
#- RULE-SET,rule_basicads,AdBlock
- RULE-SET,rule_whatsapp,Select_VIP
- RULE-SET,rule_portgames,Select_VIP
- MATCH,Global
