port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: derisamedia
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 8.8.8.8
  default-nameserver:
  - 8.8.8.8
  proxy-server-nameserver:
  - 1.1.1.1
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"


proxy-providers:
  VVIP-IPTUNNELS-FREE:
    type: http
    url: "https://raw.githubusercontent.com/marieff/cfaku/main/proxy/vvip-free.yaml"
    interval: 3600
    path: "./proxy_provider/vvip-free.yaml"
    health-check:
      enable: true
      url: https://api.v2fly.org/checkConnection.svgz
      interval: 180
  VVIP-IPTUNNELS-VIP:
    type: file
    path: "./proxy_provider/vvip-vip.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 180
  VVIP-IPTUNNELS-FOOL:
    type: http
    url: "http://fool.azurewebsites.net/get?cc=SG,ID&mode=cdn&pass=74a12fd6&format=clash&cdn=ilmupedia.mdevz.biz.id"
    interval: 3600
    path: "./proxy_provider/vvip-fool.yaml"
    health-check:
      enable: true
      url: https://api.v2fly.org/checkConnection.svgz
      interval: 180
      
rule-providers:
  rule_whatsapp:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_whatsapp.yaml
    path: "./rule_whatsapp.yaml"
    interval: 86400
  #rule_basicads:
    #type: http
    #behavior: domain
    #url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_basicads.yaml
    #path: "./rule_basicads.yaml"
    #interval: 86400
  rule_portgames:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_portgames.yaml
    path: "./rule_portgames.yaml"
    interval: 86400
  rule_bank-id:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_bank-id.yaml
    path: "./rule_bank-id.yaml"
    interval: 86400
  rule_indo:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/marieff/cfaku/main/rules/rule_indo.yaml
    path: "./rule_indo.yaml"
    interval: 86400
    
proxy-groups:
- name: Global
  type: select
  disable-udp: false
  proxies:
  - BEST-PING
  - LOAD-BALANCE
  - FALLBACK
  - PROXY-CHAIN
  - SELECT
- name: SELECT
  type: select
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
#- name: AdBlock
  #type: select
  #disable-udp: false
  #proxies:
  #- REJECT
  #- Global
- name: Select_VIP
  type: select
  disable-udp: false
  proxies:
  - BEST-PING
  - LOAD-BALANCE
  - FALLBACK
  - PROXY-CHAIN
  - REJECT
  use:
  - VVIP-IPTUNNELS-VIP
- name: LOAD-BALANCE
  type: load-balance
  strategy: round-robin
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: FALLBACK
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: BEST-PING 
  type: url-test
  tolerance: 50
  lazy: true
  disable-udp: false
  use:
  - VVIP-IPTUNNELS-FREE
  - VVIP-IPTUNNELS-VIP
  - VVIP-IPTUNNELS-FOOL
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: PROXY-CHAIN
  type: relay
  disable-udp: false
  proxies:
  - BEST-PING
  - LOAD-BALANCE
  - FALLBACK

rules:
#- RULE-SET,rule_basicads,AdBlock
- RULE-SET,rule_whatsapp,Select_VIP
- RULE-SET,rule_portgames,Select_VIP
- MATCH,Global
